name:                           coverage

on:                             [push]
jobs:
  test:
    name:                       coverage
    runs-on:                    ubuntu-latest
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2

      - name: Setup
        run: sudo apt-get update && sudo apt-get install libsdl2-dev

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name:                   Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --out Xml

      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v1
        with:
          fail_ci_if_error:     true
